import hashlib
import argparse
import requests

"""Download file and check it SHA256."""
def download_and_calculate_sha256(url: str) -> str:
    response = requests.get(url, stream=True)
    response.raise_for_status()

    sha256_hash = hashlib.sha256()
    total_size = 0
    for chunk in response.iter_content(chunk_size=8192):
        if chunk:
            sha256_hash.update(chunk)
            total_size += len(chunk)

    return sha256_hash.hexdigest()


"""Generate Homebrew Formula from source files"""


def generate_formula(
        version: str,
        source_sha256: str,
        repo: str,
        description: str,
        license: str
) -> str:
    formula = f'''
    # This file is auto-generated by script/generate_homebrew_formula.py
    # DO NOT EDIT MANUALLY
    
    class Wrench < Formula
      desc "{description}"
      homepage "{repo}"
      url "{repo}/archive/refs/tags/{version}.tar.gz"
      sha256 "{source_sha256}"
      license "{license}"
    
      depends_on "ghc" => :build
      depends_on "haskell-stack" => :build
    
      def install
        system "stack", "build", "--copy-bins", "--local-bin-path", "#{{buildpath}}/bin"
        bin.install Dir["bin/*"]
      end
    
      test do
        system "#{{bin}}/wrench", "--version"
      end
    end
    '''
    return formula


def main():
    parser = argparse.ArgumentParser(description="Generate Homebrew formula from source")

    parser.add_argument(
        "--version",
        required=True,
        help="Version of the release"
    )

    parser.add_argument(
        "--repo",
        default="https://github.com/ryukzak/wrench",
        help="Repository URL"
    )

    parser.add_argument(
        "--output",
        default="./wrench.rb",
        help="Output file path"
    )

    parser.add_argument(
        "--description",
        default="An educational project designed to explore different types of processor architectures. It includes simple CPU models and assemblers for them.",
        help="Formula description"
    )

    parser.add_argument(
        "--license",
        default="BSD-3-Clause",
        help="SPDX license identifier"
    )

    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip downloading source archive (use provided SHA256)"
    )

    parser.add_argument(
        "--sha256",
        help="SHA256 of source archive (use with --skip-download)"
    )

    args = parser.parse_args()

    source_url = f"{args.repo}/archive/refs/tags/{args.version}.tar.gz"

    if args.skip_download and args.sha256:
        sha256 = args.sha256
        print(f"Using provided SHA256")
    else:
        sha256 = download_and_calculate_sha256(source_url)
        print(f"SHA256: {sha256}")

    # Generate homebrew formula
    formula = generate_formula(
        version=args.version,
        source_sha256=sha256,
        repo=args.repo,
        description=args.description,
        license=args.license
    )

    with open(args.output, "w") as f:
        f.write(formula)

    print(f"""
    Formula generated: {args.output},
    Version: {args.version} 
    """)


if __name__ == "__main__":
    main()
