import hashlib
import argparse
import requests
import json
from typing import Dict, Optional

def download_and_calculate_sha256(url: str) -> str:
    """Download file and calculate its SHA256."""
    response = requests.get(url, stream=True)
    response.raise_for_status()

    sha256_hash = hashlib.sha256()
    total_size = 0
    for chunk in response.iter_content(chunk_size=8192):
        if chunk:
            sha256_hash.update(chunk)
            total_size += len(chunk)

    print(f"Downloaded {total_size} bytes from {url}")
    return sha256_hash.hexdigest()

def normalize_version(version: str) -> str:
    """Normalize version string by removing refs/tags/ prefix."""
    version = version.replace("refs/tags/", "")
    version = version.lstrip("v")
    return version

def get_bottle_key(asset_name: str) -> Optional[str]:
    """
    Convert asset filename to Homebrew bottle key.

    Examples:
    - wrench-Linux-ARM64.tar.gz -> arm64_linux
    - wrench-Linux-X64.tar.gz -> x86_64_linux
    - wrench-macOS-ARM64.tar.gz -> arm64_ventura
    - wrench-Windows-X64.tar.gz -> None (Windows not supported)
    """
    base_name = asset_name.replace('.tar.gz', '')
    parts = base_name.split('-')

    if len(parts) < 3:
        print(f"Warning: Cannot parse asset name: {asset_name}")
        return None

    # parts[0] = "wrench", parts[1] = OS, parts[2] = ARCH
    os_name = parts[1].lower()
    arch = parts[2].lower()

    if os_name == 'windows':
        print(f"Skipping Windows asset: {asset_name}")
        return None

    if os_name == 'macos':
        if arch == 'arm64':
            return 'arm64_ventura'
        elif arch == 'x64':
            return 'x86_64'
        else:
            print(f"Unknown macOS arch: {arch}")
            return None
    elif os_name == 'linux':
        if arch == 'arm64':
            return 'arm64_linux'
        elif arch == 'x64':
            return 'x86_64_linux'
        else:
            print(f"Unknown Linux arch: {arch}")
            return None
    else:
        print(f"Unknown OS: {os_name}")
        return None

def generate_formula(
        version: str,
        repo: str,
        description: str,
        license: str,
        source_sha256: str
) -> str:
    """Generate Homebrew formula with manual binary download."""

    formula = f'''# This file is auto-generated by script/generate_homebrew_formula.py
# DO NOT EDIT MANUALLY

class Wrench < Formula
  desc "{description}"
  homepage "https://github.com/{repo}"
  url "https://github.com/{repo}/archive/refs/tags/{version}.tar.gz"
  sha256 "{source_sha256}"
  license "{license}"

  depends_on "ghc" => :build
  depends_on "haskell-stack" => :build

  def install
    # Determine architecture and OS
    arch = Hardware::CPU.arm? ? "ARM64" : "X64"
    os = OS.mac? ? "macOS" : "Linux"
    
    # Build filename and URL
    filename = "wrench-#{{os}}-#{{arch}}.tar.gz"
    url = "https://github.com/{repo}/releases/download/#{{version}}/#{{filename}}"
    
    # Download binary
    odie "Failed to download #{{url}}" unless system "curl", "-L", url, "-o", filename
    
    # Extract
    system "tar", "xzf", filename
    
    # Install binary
    bin.install "wrench"
  end

  test do
    system "#{{bin}}/wrench", "--version"
  end
end
'''
    return formula

def main():
    parser = argparse.ArgumentParser(description="Generate Homebrew formula from source")

    parser.add_argument("--version", required=True, help="Version of the release")
    parser.add_argument("--repo", required=True, help="Repository URL")
    parser.add_argument("--output", default="./wrench.rb", help="Output file path")
    parser.add_argument("--description", default="An educational project designed to explore different types of processor architectures.", help="Formula description")
    parser.add_argument("--license", default="BSD-3-Clause", help="SPDX license identifier")
    parser.add_argument("--assets", help="JSON list of asset filenames")
    parser.add_argument("--source-sha256", help="SHA256 of source archive")

    args = parser.parse_args()

    repo = args.repo.replace("https://github.com/", "").rstrip("/")
    version = normalize_version(args.version)

    source_url = f"https://github.com/{repo}/archive/refs/tags/{version}.tar.gz"
    if args.source_sha256:
        source_sha256 = args.source_sha256
    else:
        source_sha256 = download_and_calculate_sha256(source_url)
        print(f"Source SHA256: {source_sha256}")

    assets = []
    if args.assets:
        try:
            assets = json.loads(args.assets)
            print(f"Parsed {len(assets)} assets")
        except json.JSONDecodeError as e:
            print(f"Error parsing assets JSON: {e}")
            assets = []

    bottle_assets = {}
    if assets:
        base_url = f"https://github.com/{repo}/releases/download/{version}"
        for asset in assets:
            if 'Source' not in asset and asset.endswith('.tar.gz'):
                bottle_assets[asset] = f"{base_url}/{asset}"

    formula = generate_formula(
        version=version,
        repo=repo,
        description=args.description,
        license=args.license,
        bottle_assets=bottle_assets,
        source_sha256=source_sha256
    )

    with open(args.output, "w") as f:
        f.write(formula)

    print(f"""
    Formula generated: {args.output},
    Version: {args.version} 
    """)


if __name__ == "__main__":
    main()