import hashlib
import argparse
import requests
import json
from typing import Dict, List


def download_and_calculate_sha256(url: str) -> str:
    """Download file and calculate its SHA256."""
    response = requests.get(url, stream=True)
    response.raise_for_status()

    sha256_hash = hashlib.sha256()
    for chunk in response.iter_content(chunk_size=8192):
        if chunk:
            sha256_hash.update(chunk)

    return sha256_hash.hexdigest()


def normalize_version(version: str) -> str:
    """Normalize version string by removing refs/tags/ prefix."""
    version = version.replace("refs/tags/", "")
    version = version.lstrip("v")
    return version


def get_asset_urls(repo: str, version: str, assets: List[str]) -> Dict[str, str]:
    """Get download URLs for assets from GitHub release."""
    base_url = f"https://github.com/{repo}/releases/download/{version}"
    return {asset: f"{base_url}/{asset}" for asset in assets}


def generate_formula(
        version: str,
        repo: str,
        description: str,
        license: str,
        bottle_assets: Dict[str, str],
        source_sha256: str = None
) -> str:
    """Generate Homebrew formula with bottle block."""

    """Create bottle block for fast installation from builds"""
    bottle_lines = []
    for asset_name, url in bottle_assets.items():
        parts = asset_name.replace('.tar.gz', '').split('-')
        if len(parts) >= 3:
            os_name = parts[1].lower()
            arch = parts[2].lower()

            if arch == 'arm64' and os_name == 'macos':
                bottle_key = 'arm64_ventura'
            elif arch == 'x64' and os_name == 'linux':
                bottle_key = 'x86_64_linux'
            elif arch == 'arm64' and os_name == 'linux':
                bottle_key = 'arm64_linux'
            elif arch == 'x64' and os_name == 'windows':
                bottle_key = 'x86_64'

            if os_name != 'windows':
                sha256 = download_and_calculate_sha256(url)
                bottle_lines.append(f'    sha256 "{sha256}" => :{bottle_key}')

    bottle_block = f'''
  bottle do
    root_url "{f"https://github.com/{repo}/releases/download/{version}"}"
{bottle_lines[0] if bottle_lines else "    # No bottles available"}
  end
'''

    formula = f'''
# This file is auto-generated by script/generate_homebrew_formula.py
# DO NOT EDIT MANUALLY

class Wrench < Formula
  desc "{description}"
  homepage "https://github.com/{repo}"
  url "https://github.com/{repo}/archive/refs/tags/{version}.tar.gz"
  sha256 "{source_sha256}"
  license "{license}"
{bottle_block}
  depends_on "ghc" => :build
  depends_on "haskell-stack" => :build

  def install
    system "stack", "build", "--copy-bins", "--local-bin-path", "#{{buildpath}}/bin"
    bin.install Dir["bin/*"]
  end

  test do
    system "#{{bin}}/wrench", "--version"
  end
end
'''
    return formula


def main():
    parser = argparse.ArgumentParser(description="Generate Homebrew formula from source")

    parser.add_argument("--version", required=True, help="Version of the release")
    parser.add_argument("--repo", required=True, help="Repository URL")
    parser.add_argument("--output", default="./wrench.rb", help="Output file path")
    parser.add_argument("--description", default="An educational project designed to explore different types of processor architectures.", help="Formula description")
    parser.add_argument("--license", default="BSD-3-Clause", help="SPDX license identifier")
    parser.add_argument("--assets", help="JSON list of asset filenames")
    parser.add_argument("--source-sha256", help="SHA256 of source archive")

    args = parser.parse_args()

    repo = args.repo.replace("https://github.com/", "").rstrip("/")
    version = normalize_version(args.version)

    source_url = f"https://github.com/{repo}/archive/refs/tags/{version}.tar.gz"
    if args.source_sha256:
        source_sha256 = args.source_sha256
    else:
        source_sha256 = download_and_calculate_sha256(source_url)

    assets = []
    if args.assets:
        assets = json.loads(args.assets)

    bottle_assets = {}
    if assets:
        base_url = f"https://github.com/{repo}/releases/download/{version}"
        for asset in assets:
            if asset.endswith('.tar.gz') and 'Source' not in asset:
                bottle_assets[asset] = f"{base_url}/{asset}"

    formula = generate_formula(
        version=version,
        repo=repo,
        description=args.description,
        license=args.license,
        bottle_assets=bottle_assets,
        source_sha256=source_sha256
    )

    with open(args.output, "w") as f:
        f.write(formula)

    print(f"""
    Formula generated: {args.output},
    Version: {args.version} 
    """)


if __name__ == "__main__":
    main()
